name: dd_taoke_sdk
description: ddshop 的 sdk
version: 1.5.8
homepage: https://github.com/mdddj/flutter_dd_dataoke_sdk

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  dio: any
  get: any
  logger: any

  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: shop.itbug.dd_taoke_sdk
        pluginClass: DdTaokeSdkPlugin
      ios:
        pluginClass: DdTaokeSdkPlugin

